// <auto-generated />
using System;
using BillColl_Main.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillColl_Main.Migrations
{
    [DbContext(typeof(myDBContext))]
    [Migration("20220317170219_UpdateBankdetailsv2")]
    partial class UpdateBankdetailsv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BillColl_Main.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Branch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwiftCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountName = "Isla Lipana and Co.",
                            AccountNumber = " 3691-0000-27 - Current account-Peso \n 3694-0001-25(Dollar account)",
                            BankName = "Bank of the Philippine Islands",
                            Branch = "Malate, Metro Manila, Philippines",
                            SwiftCode = "BOPIPHMM"
                        },
                        new
                        {
                            Id = 2,
                            AccountName = "Isla Lipana and Co.",
                            AccountNumber = "001688052218 - Current Account Peso",
                            BankName = "BDO Unibank, Inc.",
                            Branch = "BDO Philam Tower- Valero Branch",
                            SwiftCode = "BNORPHMM"
                        },
                        new
                        {
                            Id = 3,
                            AccountName = "PricewaterhouseCoopers Consulting Services Philippines Co.Ltd..",
                            AccountNumber = " 99196741877 - Current account-Peso \n 9010196927767 - SA-(Dollar account)",
                            BankName = "Standard Chartered Bank",
                            Branch = "Ayala, Makati City",
                            SwiftCode = "SCBLPHMM"
                        },
                        new
                        {
                            Id = 4,
                            AccountName = "Cabrera & Company",
                            AccountNumber = " 0031-0681-69 - Current account-Peso \n 0034-0280-95 - (Dollar Account)",
                            BankName = "Bank of the Philippine Islands",
                            Branch = "Paseo de Roxas, Makati City",
                            SwiftCode = "BOPIPHMM"
                        });
                });

            modelBuilder.Entity("BillColl_Main.Models.BankPHEntity", b =>
                {
                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("PHEntityId")
                        .HasColumnType("int");

                    b.HasKey("BankId", "PHEntityId");

                    b.HasIndex("PHEntityId");

                    b.ToTable("BankPHEntity");

                    b.HasData(
                        new
                        {
                            BankId = 1,
                            PHEntityId = 1
                        },
                        new
                        {
                            BankId = 2,
                            PHEntityId = 1
                        },
                        new
                        {
                            BankId = 3,
                            PHEntityId = 4
                        },
                        new
                        {
                            BankId = 4,
                            PHEntityId = 2
                        });
                });

            modelBuilder.Entity("BillColl_Main.Models.ClientRemarks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StatementDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ClientRemarks");
                });

            modelBuilder.Entity("BillColl_Main.Models.Contacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("BillColl_Main.Models.EngagementTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("EngagementTeams");
                });

            modelBuilder.Entity("BillColl_Main.Models.Exceptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exceptions");
                });

            modelBuilder.Entity("BillColl_Main.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("BillColl_Main.Models.PHEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EntityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PHEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntityCode = "",
                            EntityName = "Isla Lipana & Co."
                        },
                        new
                        {
                            Id = 2,
                            EntityCode = "",
                            EntityName = "Cabrera & Company"
                        },
                        new
                        {
                            Id = 3,
                            EntityCode = "",
                            EntityName = "PwC WMS Pte Ltd."
                        },
                        new
                        {
                            Id = 4,
                            EntityCode = "",
                            EntityName = "PwC CONS Ltd."
                        },
                        new
                        {
                            Id = 5,
                            EntityCode = "",
                            EntityName = "PwC Services"
                        },
                        new
                        {
                            Id = 6,
                            EntityCode = "",
                            EntityName = "PwC BSP Co. Ltd."
                        });
                });

            modelBuilder.Entity("BillColl_Main.Models.BankPHEntity", b =>
                {
                    b.HasOne("BillColl_Main.Models.Bank", "Bank")
                        .WithMany("BankPHEntity")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BillColl_Main.Models.PHEntity", "PHEntity")
                        .WithMany("BankPHEntity")
                        .HasForeignKey("PHEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("PHEntity");
                });

            modelBuilder.Entity("BillColl_Main.Models.EngagementTeam", b =>
                {
                    b.HasOne("BillColl_Main.Models.Group", "Group")
                        .WithMany("EngagementTeams")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BillColl_Main.Models.Bank", b =>
                {
                    b.Navigation("BankPHEntity");
                });

            modelBuilder.Entity("BillColl_Main.Models.Group", b =>
                {
                    b.Navigation("EngagementTeams");
                });

            modelBuilder.Entity("BillColl_Main.Models.PHEntity", b =>
                {
                    b.Navigation("BankPHEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
